describe('framework APIs', () => {
  it('init', () => {})
  it('reset', () => {})
  it('createInstance', () => {})
  it('createInstance with config', () => {})
  it('createInstance with external data', () => {})
  it('destroyInstance', () => {})
  it('refreshInstance', () => {})
  it('getRoot', () => {})
  it('reveiveTasks', () => {})
  it('registerModules', () => {})
  it('registerComponents', () => {})
  it('Vue.$getConfig', () => {})
  it('Timer', () => {})
  it('send function param', () => {})
  it('send Element param', () => {})
})
